name: Maven deploy release
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven settings
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Deploy the package
        run: mvn --batch-mode deploy # skip upload